module.exports = {
  attributes: [
    {
      id: 1,
      name: 'tác giả',
      backendType: 'string',
      frontendInput: 'text',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 2,
      name: 'công ty phát hành',
      backendType: 'string',
      frontendInput: 'text',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 3,
      name: 'kích thước',
      backendType: 'string',
      frontendInput: 'text',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 4,
      name: 'dịch giả',
      backendType: 'string',
      frontendInput: 'text',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 5,
      name: 'loại bìa',
      backendType: 'string',
      frontendInput: 'text',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 6,
      name: 'số trang',
      backendType: 'int',
      frontendInput: 'number',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 7,
      name: 'nhà xuất bản',
      backendType: 'string',
      frontendInput: 'text',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 8,
      name: 'thương hiệu',
      backendType: 'string',
      frontendInput: 'text',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 9,
      name: 'xuất xứ',
      backendType: 'string',
      frontendInput: 'text',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 10,
      name: 'CPU',
      backendType: 'string',
      frontendInput: 'text',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 11,
      name: 'card đồ họa',
      backendType: 'string',
      frontendInput: 'text',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 12,
      name: 'dung lượng ổ cứng',
      backendType: 'string',
      frontendInput: 'text',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 13,
      name: 'RAM',
      backendType: 'string',
      frontendInput: 'text',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 14,
      name: 'trọng lượng sản phẩm',
      backendType: 'string',
      frontendInput: 'text',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 15,
      name: 'kích thước màn hình',
      backendType: 'string',
      frontendInput: 'text',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 16,
      name: 'camera sau',
      backendType: 'string',
      frontendInput: 'text',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 17,
      name: 'camera trước',
      backendType: 'string',
      frontendInput: 'text',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 18,
      name: 'màu',
      backendType: 'string',
      frontendInput: 'text',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 19,
      name: 'dung lượng',
      backendType: 'string',
      frontendInput: 'text',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
  attributeGroups: [
    {
      id: 1,
      name: 'sách',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 2,
      name: 'laptop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 3,
      name: 'điện thoại',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
  attributeSets: [
    {
      id: 1,
      attributeGroupId: 1,
      attributeId: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 2,
      attributeGroupId: 1,
      attributeId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 3,
      attributeGroupId: 1,
      attributeId: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 4,
      attributeGroupId: 1,
      attributeId: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 5,
      attributeGroupId: 1,
      attributeId: 5,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 6,
      attributeGroupId: 1,
      attributeId: 6,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 7,
      attributeGroupId: 1,
      attributeId: 7,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 8,
      attributeGroupId: 2,
      attributeId: 8,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 9,
      attributeGroupId: 2,
      attributeId: 9,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 10,
      attributeGroupId: 2,
      attributeId: 10,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 11,
      attributeGroupId: 2,
      attributeId: 11,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 12,
      attributeGroupId: 2,
      attributeId: 12,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 13,
      attributeGroupId: 2,
      attributeId: 13,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 14,
      attributeGroupId: 2,
      attributeId: 14,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    {
      id: 15,
      attributeGroupId: 3,
      attributeId: 15,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 16,
      attributeGroupId: 3,
      attributeId: 16,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 17,
      attributeGroupId: 3,
      attributeId: 17,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 18,
      attributeGroupId: 3,
      attributeId: 18,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 19,
      attributeGroupId: 3,
      attributeId: 19,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 20,
      attributeGroupId: 3,
      attributeId: 8,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 21,
      attributeGroupId: 3,
      attributeId: 9,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
  products: [
    {
      id: 1,
      name: 'think and grow rich - 13 nguyên tắc nghĩ giàu, làm giàu',
      sku: new Date().toISOString(),
      rate: null,
      price: 83000,
      isActive: true,
      desc: 'Cuốn sách sẽ giúp bạn trở nên giàu có,ịnh.',
      image: 'link ảnh',
      unitInStock: 100,
      unitOnOrder: 99,
      shopId: 1,
      categoryId: 1,
      attributeGroupId: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 2,
      name: 'iphone 14 pro',
      sku: new Date().toISOString(),
      rate: null,
      price: 32000000,
      isActive: true,
      desc: 'Thanh lịch, hiệniện.',
      image: 'link ảnh',
      unitInStock: 17,
      unitOnOrder: 15,
      shopId: 1,
      categoryId: 2,
      attributeGroupId: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
  productVarchar: [
    {
      id: 1,
      value: 'Napoleon Hill',
      productId: 1,
      attributeId: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 2,
      value: 'Thái Hà',
      productId: 1,
      attributeId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 3,
      value: '15.5 x 24 cm',
      productId: 1,
      attributeId: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 4,
      value: 'Ross Cornwell -Thảo Triều',
      productId: 1,
      attributeId: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 5,
      value: 'Bìa mềm',
      productId: 1,
      attributeId: 5,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 6,
      value: 'Nhà Xuất Bản Lao Động',
      productId: 1,
      attributeId: 7,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 7,
      value: 'Apple',
      productId: 2,
      attributeId: 8,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 8,
      value: 'Mỹ',
      productId: 2,
      attributeId: 9,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 9,
      value: '6.1 inch',
      productId: 2,
      attributeId: 15,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 10,
      value: 'Chính 48 MP & Phụ 12 MP, 12 MP',
      productId: 2,
      attributeId: 16,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 11,
      value: '12 MP',
      productId: 2,
      attributeId: 17,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 12,
      value: 'Tím',
      productId: 2,
      attributeId: 18,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 13,
      value: '128GB',
      productId: 2,
      attributeId: 19,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
  productInt: [
    {
      id: 1,
      value: '	399',
      productId: 1,
      attributeId: 6,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
  categories: [
    {
      id: 1,
      name: 'Sách',
      desc: 'Sách chứa đựng mọi thứ: kiến thức, kinh nghiệm sống và cảm xúc con người, là những viên gạch xây nên những thành tựu của con người.',
      image: 'link ảnh',
      path: '1',
      parentId: null,
      level: 1,
      childrentCount: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 2,
      name: 'Điện thoại',
      desc: 'Điện thoại là thiết bị viễn thông dùng để trao đổi thông tin, thông dụng nhất là truyền giọng nói - tức là "thoại", từ xa giữa hai hay nhiều người. Điện thoại biến tiếng nói thành tín hiệu điện và truyền trong mạng điện thoại phức tạp thông qua kết nối để đến người sử dụng khác.',
      image: 'link ảnh',
      path: '2',
      parentId: null,
      level: 1,
      childrentCount: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
  shop: [
    {
      id: 1,
      shopName: 'Hoài Nam',
      rate: 0,
      desc: 'Uy tín - Chất lượng',
      image: 'link shop',
      sellerId: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
};
